import type Voiceline from "./Voiceline"

export default interface Character {
    ID: number,
    Name: string,
    Version: string,
    Rarity: number,
    Afflatus: string,
    Race: string,
    "DMG Type": String,
    Gender: string,
    Tags: Array<string>,
    "Other Name": string,
    Image: string,
    Voicelines: {
        "First Encounter": Voiceline,
        "Suitcase Climate": Voiceline,
        "To the Future": Voiceline,
        "Idle": Voiceline,
        "Greetings": Voiceline,
        "Morning": Voiceline,
        "Bond: Morning": Voiceline,
        "Night": Voiceline,
        "Bond: Night": Voiceline,
        "Hat and Hair": Voiceline,
        "Sleeves and Hands": Voiceline,
        "Clothing and Torso": Voiceline,
        "Hobby": Voiceline,
        "Praise": Voiceline,
        "Intimacy": Voiceline,
        "Chitchat I": Voiceline,
        "Chitchat II": Voiceline,
        "Monologue": Voiceline,
        "Deployment": Voiceline,
        "Pre-Battle": Voiceline,
        "Select Incantation I": Voiceline,
        "Select Incantation II": Voiceline,
        "Select 3-star Incantation": Voiceline,
        "Select Ultimate": Voiceline,
        "Cast Arcane Skill I": Voiceline,
        "Cast Arcane Skill II": Voiceline,
        "Cast Ultimate": Voiceline,
        "Attacked I"?: Voiceline,
        "Attacked II"?: Voiceline,
        "Battle Victory": Voiceline,
        "Insight": Voiceline,
        "Bottom of Insight"?: Voiceline
    }
}